[project]
name = "project-423"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "autopep8>=2.3.1",
    "complexipy>=0.4.0",
    "pylint",
    "pytest>=5.0.0",
    "pytest-cov",
    "streamlit>=1.38.0",
]
